[project]
name = "l4-query"
version = "0.1.0"
description = "Add a short description here"
authors = ["ymh <hanyongming@gmail.com>"]
channels = ["conda-forge", "pytorch"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
# When using pypi-dependencies, python is needed to resolve pypi dependencies
# make sure to include this
python = ">=3.11"
instructor = ">=1.3.2,<1.4"
ipython = ">=8.25.0,<8.26"
litellm = ">=1.39.6,<1.40"
ujson = ">=5.10.0,<5.11"
mypy = ">=1.10.0,<1.11"
toolz = ">=0.12.1,<0.13"
rich = ">=13.7.1,<13.8"
structlog = ">=24.2.0,<24.3"
packaging = ">=24.0,<25"
outlines = ">=0.0.41,<0.1"
faiss-cpu = ">=1.7.4,<1.8"

[pypi-dependencies]
fasttext = {git = "https://github.com/cfculhane/fastText.git#main"}
string2string = "*"
clean-text = "*"
